### ISSUE TITLE
ZeroMQException(22): EINVAL when setting the SUB socket option.

### ISSUE THREAD

**Issue by Beaverking** [enwi/dartzmq#42]
I have the SUB socket:
`subscribeSocket = m_context.createSocket(SocketType.sub);`
I then try to set the "conflate" option to it:
`subscribeSocket.setOption(ZMQ_CONFLATE, "1");`
But I get this exception:
```
ZeroMQException(22): EINVAL

0      _checkErrorCode (package:dartzmq/src/exception.dart:56:5) exception.dart:56
#1      _checkReturnCode (package:dartzmq/src/exception.dart:49:5) exception.dart:49
#2      ZBaseSocket.setOption (package:dartzmq/src/socket.dart:244:5) socket.dart:24
```
Some other functions in the socket.dart specify that I should use the Z85 encoding for the input string. Is it also the case here?
This is on Android BTW.

**Comment by enwi** [comment]
It seems that the value (string) is not expected here. Looking at the documentation a boolean is expected. We might need a different way of handling this.

**Comment by enwi** [comment]
@Beaverking can you try the latest dev branch?
